<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:doc="http://www.saxonica.com/ns/documentation"
                xmlns:err="http://www.w3.org/2005/xqt-errors"
                xmlns:f="MyFunctions"
                xmlns:ixml="http://invisiblexml.org/NS"
                xmlns:ixsl="http://saxonica.com/ns/interactiveXSLT"
                xmlns:js="http://saxonica.com/ns/globalJS"
                xmlns:jwL="https://github.com/johnlumley"
                xmlns:map="http://www.w3.org/2005/xpath-functions/map"
                xmlns:saxon="http://saxon.sf.net/"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:cs="http://nineml.com/ns/coffeesacks"
                exclude-result-prefixes="xs js  err ixml cs doc  map saxon  ixsl jwL f"
                version="4.0"
                expand-text="yes">            
         <!--DO NOT EDIT - 
            generated from file:/D:/Saxonica/InvisibleXML/Mine/dist/jwiXML.processor.4.xsl at 2025-09-06T13:51:13.2599804+01:00 by EE 12.4-->
   <!-- This global variable evaluates to the 'grammar factory' used to parse/compile iXML grammars
        to produce an iXML parser for the selected grammar.
        The jwiXML() function has been attached to the browser window object at the end of the evalution of the 
        jwiXML JavaScript library script
    -->
   <xsl:variable name="jwiXML" select="js:jwiXML()"/>
   <!-- Version identifier -->
   <xsl:function name="jwL:version" as="xs:string">
      <xsl:sequence select="ixsl:call($jwiXML, 'version', [])"/>
   </xsl:function>
   <!-- A simple cominpation of a grammar, with no preprocessing or pragma support -->
   <xsl:function name="jwL:compileGrammarSimple" as="item()" visibility="public">
      <xsl:param name="grammarSource" as="item()"/>
      <xsl:sequence select="ixsl:call($jwiXML, 'compile', [$grammarSource, map {}])"/>
   </xsl:function>
   <!--  -->
   <xsl:param name="pragmaURI"
              select="static-base-uri()"
              doc:doc="The base uri to resolve pragma implementation URIs against.          In buried pragma invocations (especially in include/import) this parameter will be passed down         from the initial top-level binding use of this stylesheet."/>
   <xsl:param name="pragmaSupport" as="element()*">
      <pragmaSupport uri="XSL/Transform">
         <pragma name="import" stylesheet="pragmas/xsl/include.xsl"/>
         <pragma name="include" stylesheet="pragmas/xsl/include.xsl"/>
         <pragma name="nur" stylesheet="pragmas/xsl/nur.xsl"/>
      </pragmaSupport>
      <pragmaSupport uri="">
            <!--<pragma name="import" stylesheet="pragmas/include.xsl"/>-->
         <pragma name="import" stylesheet="pragmas/xsl/include.xsl"/>
         <pragma name="include" stylesheet="pragmas/include.xsl"/>
         <pragma name="nur" stylesheet="pragmas/nur.xsl"/>
      </pragmaSupport>
   </xsl:param>
   <xsl:variable name="pragmas.supported"
                 as="xs:string*"
                 select="             for $n in $pragmaSupport             return                 $n/*/('Q{' || $n/@uri || '}' || @name)"/>
   <xsl:variable name="pragma.implementations"
                 as="map(*)"
                 select="             map:merge(for $n in $pragmaSupport             return                 $n/*/map:entry('Q{' || $n/@uri || '}' || @name, doc(resolve-uri(@stylesheet, $pragmaURI))))"/>
   <xsl:variable name="namespaces.supported"
                 as="xs:string*"
                 select="$pragmaSupport/@uri[.]"/>
   <!-- 
    These are the calls to compile or just parse an iXML grammar
    They use the 'grammar factory' generated by the evaluation of jwiXML() 
    bound to the global variable jwiXML above
    
        jwL:compileGrammar() produces a fully compiled grammar suitable for parsing input text strings
        jwl:parseGrammar() generates an internal parse object of the iXML grammar supplied, from which
              an XML-exported form can be retrieved via its display() method, viz:
                    ixsl:call($parsedGrammar,'display',[])  (THE NAME MAY CHANGE!)
       jwl:preprocessGrammar() generates an internal parse object of the iXML grammar supplied and then
             runs any supported pragma-declared preprocessing steps, returning either the preprocessed grammar,
             or (with $options?compile) the result of compiling that preprocessed,.
    -->
   <!--Defaulting function: jwL:compileGrammar-->
   <xsl:function name="jwL:compileGrammar" as="item()" visibility="public">
      <xsl:param name="grammarSource" as="item()"/>
      <xsl:variable name="options" as="map(*)" select="map {}"/>
      <xsl:sequence select="jwL:compileGrammar($grammarSource,$options)"/>
   </xsl:function>
   <xsl:function name="jwL:compileGrammar" as="item()" visibility="public">
      <xsl:param name="grammarSource" as="item()"/>
      <xsl:param name="options" as="map(*)"/>
      <xsl:sequence select="jwL:preprocessGrammar($grammarSource, map:put($options, 'compile', true()))"/>
   </xsl:function>
   <!--Defaulting function: jwL:preprocessGrammar-->
   <xsl:function name="jwL:preprocessGrammar" as="item()" visibility="public">
      <xsl:param name="grammarSource" as="item()"/>
      <xsl:variable name="options" as="map(*)" select="map {}"/>
      <xsl:sequence select="jwL:preprocessGrammar($grammarSource,$options)"/>
   </xsl:function>
   <xsl:function name="jwL:preprocessGrammar" as="item()" visibility="public">
      <xsl:param name="grammarSource" as="item()"/>
      <xsl:param name="options" as="map(*)"/>
      <!--    <xsl:message>jwL:preprocessGrammar:{$options?pragmas} : <!-\-{f:serialize($options)}-\->: &#xA;
            {serialize($grammarSource)}</xsl:message>-->
      <xsl:choose>
         <xsl:when test="$options?pragmas">
            <xsl:variable name="parsed.xml"
                          select="                         if ($grammarSource instance of document-node()) then                             $grammarSource                         else                             jwL:parseGrammar($grammarSource, $options) =&gt; jwL:grammarToXML()"/>
            <xsl:variable name="namespaces"
                          select="                         map:merge($parsed.xml//ppragma[@pname eq 'pragma']/pragma-data ! (let $p := tokenize(.)                         return                             map:entry($p[1], replace($p[2], '&#34;', ''))))"/>
            <!--  <xsl:message>namespaces: {f:serialize($namespaces)}</xsl:message>-->
            <xsl:variable name="Qnamespaces"
                          select="                         map:merge($parsed.xml//ppragma[starts-with(@pname, 'ns:')] !                         map:entry(substring-after(@pname, ':'), replace(pragma-data, '&#34;', '')))"/>
            <!--<xsl:message>Qnamespaces: {f:serialize($Qnamespaces)}</xsl:message>-->
            <xsl:variable name="pragmas"
                          select="($parsed.xml//pragma | $parsed.xml//ppragma)[@pname[not(. eq 'pragma') and not(starts-with(., 'ns:'))]]"/>
            <xsl:message>pragmasOriginal: {serialize($pragmas)}</xsl:message>
            <xsl:variable name="pragmas"
                          select="                         distinct-values(for $p in $pragmas                         return                             if ($namespaces($p/@pname) = $namespaces.supported) then                                 'Q{' || $namespaces($p/@pname) || '}' || tokenize($p)[1]                             else                                 if (contains($p/@pname, ':')) then                                     'Q{' || $Qnamespaces(substring-before($p/@pname, ':')) || '}' || substring-after($p/@pname, ':')                                 else                                     'Q{}' || $p/@pname)"/>
            <xsl:message>pragmasEQ: {serialize($pragmas)}</xsl:message>
            <xsl:variable name="pragmas"
                          select="distinct-values($pragmas)[. = $pragmas.supported]"/>
            <!--<xsl:variable name="pragmas" select="$pragmas[. = $pragmas.supported]"/>-->
            <xsl:message>pragmas: {$pragmas}</xsl:message>
            <xsl:choose>
               <xsl:when test="exists($pragmas)">
                  <xsl:iterate select="$pragmas.supported[. = $pragmas]">
                     <xsl:param name="source" select="$parsed.xml"/>
                     <xsl:param name="attempts" as="xs:integer" select="5"/>
                     <!--  <xsl:on-completion select="
                                    if ($options?compile) then
                                        ixsl:call($jwiXML, 'compile', [$source, map:put($options, 'pragmas', false())])
                                    else
                                        jwL:parseGrammar($source, $options)"/>-->
                     <xsl:on-completion>
                        <xsl:message>$options?compile : {$options?compile}</xsl:message>
                        <xsl:message>on-completion:{$attempts}:{serialize($source,map{'indent':true()})}</xsl:message>
                        <xsl:variable name="temp"
                                      select="                                         if ($options?compile) then                                             ixsl:call($jwiXML, 'compile', [$source, map:put($options, 'pragmas', true())])                                         else                                             ixsl:call($jwiXML, 'parse', [$source, map:put($options, 'pragmas', true())])"/>
                        <xsl:message>on-completion
                                    iXML:{jwL:grammarToIXML($temp)}</xsl:message>
                        <xsl:sequence select="$temp"/>
                     </xsl:on-completion>
                     <!-- <xsl:on-completion select="
                                if ($options?compile) then
                                ixsl:call($jwiXML, 'compile', [$source, map:put($options, 'pragmas', true())])
                                else
                                ixsl:call($jwiXML, 'parse', [$source, map:put($options, 'pragmas', true())])"/>-->
                     <xsl:variable name="pragmaTransform" select="$pragma.implementations(.)"/>
                     <!--<xsl:message>PT:{f:serialize($pragmaTransform)}</xsl:message>-->
                     <xsl:choose>
                        <xsl:when test="false() or $attempts le 0">
                           <xsl:break/>
                        </xsl:when>
                        <xsl:otherwise>
                           <xsl:next-iteration>
                              <xsl:with-param name="source"
                                              select="                                                 transform(map {                                                     'stylesheet-node': $pragmaTransform,                                                     'source-node': $source,                                                     'stylesheet-params': map {                                                         QName('', 'baseURI'): $options?baseURI,                                                         QName('', 'pragmaURI'): $pragmaURI                                                     }                                                 })?output"/>
                              <xsl:with-param name="attempts" select="$attempts - 1"/>
                           </xsl:next-iteration>
                        </xsl:otherwise>
                     </xsl:choose>
                  </xsl:iterate>
               </xsl:when>
               <xsl:otherwise>
                  <xsl:variable name="temp"
                                select="                                 ixsl:call($jwiXML, if ($options?compile) then                                     'compile'                                 else                                     'parse', [$grammarSource, map:put($options, 'pragmas', true())])"/>
                  <xsl:message>Processed: {serialize( jwL:grammarToXML($temp))}</xsl:message>
                  <xsl:sequence select="$temp"/>
               </xsl:otherwise>
            </xsl:choose>
         </xsl:when>
         <xsl:otherwise>
            <xsl:sequence select="                         ixsl:call($jwiXML, if ($options?compile) then                             'compile'                         else                             'parse', [$grammarSource, $options])"/>
         </xsl:otherwise>
      </xsl:choose>
   </xsl:function>
   <!--Defaulting function: jwL:parseGrammar-->
   <xsl:function name="jwL:parseGrammar" as="item()" visibility="public">
      <xsl:param name="grammarSource" as="item()"/>
      <xsl:variable name="options" as="map(*)" select="map {}"/>
      <xsl:sequence select="jwL:parseGrammar($grammarSource,$options)"/>
   </xsl:function>
   <xsl:function name="jwL:parseGrammar" as="item()" visibility="public">
      <xsl:param name="grammarSource" as="item()"/>
      <xsl:param name="options" as="map(*)"/>
      <xsl:sequence select="ixsl:call($jwiXML, 'parse', [$grammarSource, $options])"/>
   </xsl:function>
   <!-- 
        Generate an XML form of an iXML grammar object
    -->
   <xsl:function name="jwL:grammarToXML">
      <xsl:param name="grammar"
                 as="item()"
                 doc:doc="A JavaScript iXML grammar object, either from raw parsing, preprocessing or compiled"/>
      <xsl:sequence select="ixsl:call($grammar, 'display', [])"/>
   </xsl:function>
   <!-- 
        Generate an iXML form of an iXML grammar object
    -->
   <xsl:function name="jwL:grammarToIXML">
      <xsl:param name="grammar"
                 as="item()"
                 doc:doc="A JavaScript iXML grammar object, either from raw parsing, preprocessing or compiled"/>
      <xsl:sequence select="ixsl:call($grammar, 'flat', [])"/>
   </xsl:function>
   <!-- 
    These are the calls to parse an input string against a compiled grammar
    $options is a map of control options, currently supporting:
    
        justOne - xs:boolean - if true in the case of ambiguity only a single parse tree is generated,
                       though it is marked as @ixml:state="ambiguous"
        suppressMarks - xs:boolean - if true marks for ignore (-), attribute (@) or insertion (+) serialisation 
                       are not honoured but rather placed on the full parse tree output either as an @ixml:mark attribute
                       or an ixml:insert element. This ony applies to marks on the original grammar and not to
                       artefactual marks, such as used for generated non-terminals for optionality or repetition.
        twRewrites - xs:boolean - use the Tovey-Walsh rewrite rule for f+ constructs, rather than that given in the spec.
                        (This will likely be the default in future - seems to be O(5x) faster)
        
    The result is a map with the following main entries:
        
        parsed - xs:boolean - whether the input could be parsed as a sentence in the grammar
        tree - document-node() - the principal parse tree of the result, or an error report in the case of parsing failure
        allTrees - document-node()+ - the ambiguous alternative trees in case of ambiguity
                        allTrees[1] and tree should be the same document
     
     In addition an entry 'failed' will exist in the case of a failure to parse containing relevant information
     and an entry 'error-code' in the case where an error-code is available. This information will also be
     repeated in the 'tree' document as text and/or an attribute.
     
     There are other fields relevant to debugging and timing performance.
     
    -->
   <!--Defaulting function: jwL:parse-->
   <xsl:function name="jwL:parse" as="map(*)" visibility="public">
      <xsl:param name="grammar"/>
      <xsl:param name="input" as="xs:string"/>
      <xsl:variable name="options" as="map(*)" select="map {}"/>
      <xsl:sequence select="jwL:parse($grammar,$input,$options)"/>
   </xsl:function>
   <xsl:function name="jwL:parse" as="map(*)" visibility="public">
      <xsl:param name="grammar"/>
      <xsl:param name="input" as="xs:string"/>
      <xsl:param name="options" as="map(*)"/>
      <xsl:sequence select="ixsl:call($grammar, 'parse', [$input, $options])"/>
   </xsl:function>
   <!-- 
        Parse a string repeatedly, using a compiled grammar. 
        This is used for performance testing purposes.
        The result is a map as usual, with an additional entry 'others' as xs:double*
        which is a sequence of the parsing times for each repetition 
    -->
   <!--Defaulting function: jwL:parse-repeat-->
   <xsl:function name="jwL:parse-repeat" as="map(*)" visibility="public">
      <xsl:param name="grammar"/>
      <xsl:param name="input" as="xs:string"/>
      <xsl:variable name="options" as="map(*)" select="map {}"/>
      <xsl:sequence select="jwL:parse-repeat($grammar,$input,$options)"/>
   </xsl:function>
   <xsl:function name="jwL:parse-repeat" as="map(*)" visibility="public">
      <xsl:param name="grammar"/>
      <xsl:param name="input" as="xs:string"/>
      <xsl:param name="options" as="map(*)"/>
      <!--<xsl:variable name="repeats" select="$options?repeats otherwise 0"/>-->
      <xsl:variable name="repeats" select="($options?repeats, 0)[1]"/>
      <xsl:variable name="result"
                    select="jwL:parse($grammar, $input, $options)"
                    as="map(*)"/>
      <xsl:variable name="others" as="xs:double*">
         <xsl:for-each select="1 to $repeats">
            <xsl:sequence select="                         if (saxon:timestamp() gt xs:dateTimeStamp('1900-01-01T00:00:00-05:00')) then                             jwL:parse($grammar, $input, $options)?parseTime                         else                             ()"/>
         </xsl:for-each>
      </xsl:variable>
      <ixsl:set-property name="extra" select="array {$others}" object="$result"/>
      <xsl:sequence select="$result"/>
   </xsl:function>
   <!-- 
    These are the calls to parse an input string consisting of a sequence of records,
    each record being parsed separately against a compiled grammar.
    $separator - xs:string - a regular expression to define the record-separating string
    $options is a map of control options, as defined above, though at present justOne is effectively treated as true no matter what the setting,
    -->
   <!--Defaulting function: jwL:parseRecords-->
   <xsl:function name="jwL:parseRecords" as="element()*" visibility="public">
      <xsl:param name="grammar"/>
      <xsl:param name="input" as="xs:string"/>
      <xsl:variable name="separator" as="xs:string" select="'\n'"/>
      <xsl:sequence select="jwL:parseRecords($grammar,$input,$separator)"/>
   </xsl:function>
   <xsl:function name="jwL:parseRecords" as="element()*" visibility="public">
      <xsl:param name="grammar"/>
      <xsl:param name="input" as="xs:string"/>
      <xsl:param name="separator" as="xs:string"/>
      <xsl:variable name="options" as="map(*)" select="map {}"/>
      <xsl:sequence select="jwL:parseRecords($grammar,$input,$separator,$options)"/>
   </xsl:function>
   <xsl:function name="jwL:parseRecords" as="element()*" visibility="public">
      <xsl:param name="grammar"/>
      <xsl:param name="input" as="xs:string"/>
      <xsl:param name="separator" as="xs:string"/>
      <xsl:param name="options" as="map(*)"/>
      <xsl:variable name="nRecords" select="($options?nRecords,4000)[1]"/>
      <xsl:variable name="use-records"
                    select="subsequence(tokenize($input, $separator),1,$nRecords)"/>
      <xsl:choose>
         <xsl:when test="$options?showTimes">
            <xsl:iterate select="$use-records">
               <xsl:param name="records" select="0"/>
               <xsl:param name="tokens" select="0"/>
               <xsl:param name="parseTime" select="0"/>
               <xsl:param name="treeTime" select="0"/>
               <xsl:param name="states" select="0"/>
               <!--<xsl:on-completion>
                        <p class="timing">Records: {$records}, Tokens: {$tokens}, Parse time:
                            {f:roundTime($parseTime)}ms, Tree time: {f:roundTime($treeTime)}ms<br/>
                            #states: {$states}</p>
                    </xsl:on-completion>-->
               <xsl:variable name="result" select="ixsl:call($grammar, 'parse', [., $options])"/>
               <xsl:sequence select="$result?tree/*"/>
               <!-- <tokens n="{string-length(.)}"/>
            <xsl:sequence select="f:showTimes($result)"/>-->
               <xsl:next-iteration>
                  <xsl:with-param name="records" select="$records + 1"/>
                  <xsl:with-param name="tokens" select="$tokens + string-length(.)"/>
                  <xsl:with-param name="parseTime" select="$parseTime + $result?parseTime"/>
                  <xsl:with-param name="treeTime" select="$treeTime + $result?treeTime"/>
                  <xsl:with-param name="states"
                                  select="                                 $states + sum(for $s in $result?states                                 return                                     ixsl:call($s, 'countStates', []))"/>
               </xsl:next-iteration>
            </xsl:iterate>
         </xsl:when>
         <xsl:otherwise>
            <xsl:for-each select="$use-records">
               <xsl:sequence select="ixsl:call($grammar, 'parse', [., $options])?tree/*"/>
            </xsl:for-each>
         </xsl:otherwise>
      </xsl:choose>
   </xsl:function>
   <!-- An implementation of fn:invisible-xml() from QT4 
        Defined in the jwl: namespace but with the same signature-->
   <!--Defaulting function: jwL:invisible-xml-->
   <xsl:function name="jwL:invisible-xml" as="function(xs:string) as document-node()">
      <xsl:variable name="grammar" as="item()?" select="()"/>
      <xsl:sequence select="jwL:invisible-xml($grammar)"/>
   </xsl:function>
   <xsl:function name="jwL:invisible-xml" as="function(xs:string) as document-node()">
      <xsl:param name="grammar" as="item()?"/>
      <xsl:variable name="options" as="map(*)?" select="map {}"/>
      <xsl:sequence select="jwL:invisible-xml($grammar,$options)"/>
   </xsl:function>
   <xsl:function name="jwL:invisible-xml" as="function(xs:string) as document-node()">
      <xsl:param name="grammar" as="item()?"/>
      <xsl:param name="options" as="map(*)?"/>
      <xsl:try>
         <xsl:choose>
            <xsl:when test="empty($grammar)">
               <xsl:sequence select="                             function ($input as xs:string) as item() {                                 let $result := jwL:parseGrammar($input)                                 return                                     jwL:grammarToXML($result)                             }"/>
            </xsl:when>
            <xsl:otherwise>
               <xsl:variable name="compiled" select="jwL:compileGrammarSimple($grammar)"/>
               <xsl:sequence select="function ($input as xs:string) as item()
                                     {
                                         let    $result := jwL:parse($compiled, $input, map {'justOne': false()})
                                         return if ($options?fail-on-error and $result?failed)
                                                then error(QName('http://www.w3.org/2005/xqt-errors', 'FOIX0002'), 'Failure to parse: ' || $result?failed)
                                                else $result?tree
                                     }"/>
            </xsl:otherwise>
         </xsl:choose>
         <xsl:catch errors="err:FOIX0002"
                    select="error($err:code, $err:description, $err:value)"/>
         <xsl:catch errors="*"
                    select="error(QName('http://www.w3.org/2005/xqt-errors', 'FOIX0001'), 'Invalid iXML grammar: ' || $err:description)"/>
      </xsl:try>
   </xsl:function>
</xsl:stylesheet>
